export const dogfood = [
{
id: 1,
title: "Purenatural Puppy Chicken",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/8b/purenatural-puppy-chicken_39575-8b.jpg",
originalPrice: 12,
salePrice: 8.95,
rating: 4.5,
},
{
id: 2,
title: "Brit Care Adult Small Breed Lamb & Rice",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/6f/brit-care-adult-small-breed-lamb-rice-6f.jpg",
originalPrice: 11,
salePrice: null,
rating: 5,
},
{
id: 3,
title: "Nutrima Dog Health Digestion",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/42/nutrima-dog-health-digestion_42458-42.jpg",
originalPrice: 24,
salePrice: null,
rating: 5,
},
{
id: 4,
title: "Purenatural Dog Adult Sensitive Salmon with Trout",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/29/purenatural-dog-adult-sensitive-salmon-with-trout_39583-29.jpg",
originalPrice: 20,
salePrice: 15.95, 
rating: 4.5,
},
{
id: 5,
title: "Purenatural Dog Adult Grain Free Lamb",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/e8/purenatural-dog-adult-grain-free-lamb_41040-e8.jpg",
originalPrice: 17,
salePrice: null,
rating: 5    
},
{
id: 6,
title: "Canagan Country Game",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/62/canagan-country-game-62.jpg",
originalPrice: 26,
salePrice: 17.95,
rating: 5,
},
{
id: 7,
title: "Acana Dog Singles Grass-Fed Lamb",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/da/acana-dog-singles-grass-fed-lamb-da.jpg",
originalPrice: 38,
salePrice: 30,
rating: 4,
},
{
id: 8,
title: "Orijen Dog Original",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/5b/orijen-dog-original-5b.jpg",
originalPrice: 40,
salePrice: 35,
rating: 4.5,    
},
{
id: 9,
title: "Canagan Grass Fed Lamb",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/ca/canagan-grass-fed-lamb-ca.jpg",
originalPrice: 26,
salePrice: 19.95,
rating: 4.5,    
},
{
id: 10,
title: "Bozita Robur Mother & Puppy",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/d1/robur-mother-amp-puppy-d1.jpg",
originalPrice: 14,
salePrice: null,
rating: 5,    
},
{
id: 11,
title: "Acana Dog Adult",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/35/acana-dog-adult-35.jpg",
originalPrice: 60,
salePrice: 45.95,
rating: 5,    
},
{
id: 12,
title: "Purina Pro Plan Veterinary Diets Dog HA Hypoallergenic",
url: "https://get.musti.media/shops/mse/resources/ftp/productpage/10/purina-pro-plan-veterinary-diet-dog-ha-hypoallergenic-10.jpg",
originalPrice: 40,
salePrice: 29.95,
rating: 4.5,    
},
];